### PR TITLE
fix: init after `__wasm_call_ctors`

### LINKED ISSUE #15: Initialization order regression
We yesterday spent half of the day chasing down a weird new bug in a large project, which ended up narrowing down to a regression in emnapi. Git bisect ended up pointing to aa2af0813e84954b78d443f40d8b1927f879a906.

Basically, that commit somewhat changed the ordering of init.

For background, any functions marked by `__attribute__((constructor))` in C/C++ end up added to a special `__wasm_call_ctors` function and Emscripten adds them to the init array via `addOnInit`.

`addOnInit` runs init functions in the reverse order, so `__wasm_call_ctors` - which is added last - is always expected to be invoked first.

That was true with emnapi before, but after the change in that commit emnapi's initialization invokes `addOnInit` later in the process, which means - due to reverse order - the callback will now be actually invoked first, invoking the NAPI module init before `__wasm_call_ctors`, and so before the C/C++ is actually ready.

I've added a failing regression test in https://github.com/toyobayashi/emnapi/pull/14 to demonstrate the behaviour, but I'll leave the fix to you as I'm not as closely familiar with the codebase.

### PR DESCRIPTION
**Pull request by toyobayashi**
Fixes #15

### CODE REVIEW

File: packages/emnapi/src/init.ts [hunk 1]
```diff
@@ -179,7 +179,7 @@ mergeInto(LibraryManager.library, {
       return emnapiExports
     }
 
-    addOnInit(function (Module) {
+    __ATINIT__.push(function (Module) {
```
Comment (RReverser) [inline packages/emnapi/src/init.ts:182]: Wouldn't it be easier to do all this init from C/C++ rather than by dealing with JS helpers?

For example, this callback could be just another `__attribute__((constructor))` instead of adding it as a separate init from JS, and then all those surrounding calls would probably be simpler & smaller when express via napi.h too.

Comment (toyobayashi) [reply packages/emnapi/src/init.ts:182]: This callback will not be called until [`addRunDependency("emnapi-init")`](https://github.com/toyobayashi/emnapi/blob/main/packages/emnapi/src/init.ts#L118) is removed, it's asynchronous

Comment (RReverser) [reply packages/emnapi/src/init.ts:182]: Hm why? Is there anything in actual N-API that is asynchronous?

Comment (toyobayashi) [reply packages/emnapi/src/init.ts:182]: https://github.com/toyobayashi/emnapi/blob/b7501570eebd9acfbe362aeadd7168e7df688e96/packages/emnapi/src/init.ts#L117-L129

https://github.com/toyobayashi/emnapi/blob/b7501570eebd9acfbe362aeadd7168e7df688e96/packages/emnapi/src/init.ts#L26

`emnapiRuntimeInit` (async)  then `emnapiInit` (`__ATINIT__.push()`)

Comment (toyobayashi) [reply packages/emnapi/src/init.ts:182]: `emnapiInit` depends `emnapiRt` and `emnapiCtx`, which is asynchronously initialized in `emnapiRuntimeInit`

Comment (RReverser) [reply packages/emnapi/src/init.ts:182]: Hm, but then, C/C++, including `__attribute__((constructor))`, also won't be called until `addRunDependency` is removed, so the effect should be the same?

Comment (toyobayashi) [reply packages/emnapi/src/init.ts:182]: But we always need to create `Env` and export `emnapiExport` on JavaScript side, current implementation can easily use closure to save variables. (I found out Node.js official `node_api.h` uses `__attribute__((constructor))` only on native platforms, but export `napi_register_wasm_v1` on wasm, during initialization the host environment should pass `env` and `export` to it.)

https://github.com/nodejs/node/blob/513c15147cb44d2d27073e520820146185c45638/src/node_api.h#L76-L107
